#!/usr/bin/env python3
"""Deterministically generate the v0.2 DAGR SRS verification-report fixtures.

Six local fixtures: one signed DAGR MCP admission receipt for each of the five
declared ``subject_ref_origin`` values, plus one that genuinely omits the field
and therefore discloses ``not_declared``.

Everything here is deterministic. The signing key is derived from a fixed,
published seed string (see ``SIGNING_SEED_LABEL``) so the receipt bytes, and
therefore every hash in every generated report, reproduce exactly on any
machine. It is a fixture key with no authority: it signs nothing outside this
contract directory and appears in no trust bundle other than the one it
generates.

The reports are generated by calling the real verification path
(``arcs_verify.verifier.verify_receipt``) and the real v0.2 builder. They are
never hand-authored.

Execution identity is an input, never a guess. ``--verifier-commit`` is
mandatory and must be a full 40-hex lowercase commit SHA matching the report
contract's own ``verifier_commit`` pattern. There is no branch-base default, no
implicit HEAD lookup, and no repository-state fallback: this script never
inspects git. Every report it writes carries exactly the commit it was given.

``--output-dir`` is mandatory for the same reason. Writing is an explicit
choice, so a temporary generation into a test directory can never be confused
with the authoritative golden surface.

Authoritative v0.2 report goldens are produced by the post-merge closure PR,
with the exact implementation squash-merge commit::

    python tools/generate_dagr_report_v0_2_goldens.py \\
      --verifier-commit <IMPLEMENTATION_MERGE_COMMIT> \\
      --output-dir arcs_verify/contracts/dagr-srs-verification-report-v0-2/golden

The v0.1 contract directory is frozen; this script never writes to it.
"""

from __future__ import annotations

import argparse
import base64
import copy
import hashlib
import json
import re
import sys
from pathlib import Path

import rfc8785
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from arcs_verify import dagr_report_v0_2 as dr2
from arcs_verify.subject_ref_origin import DECLARED_ORIGINS, NOT_DECLARED
from arcs_verify.verifier import MCP_PROFILE, verify_receipt

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_V0_2_1 = ROOT / "arcs_verify" / "data" / "srs-envelope-v0.2.1.schema.json"

#: The report contract's own ``verifier_commit`` pattern, restated here so the
#: generator rejects anything the contract would reject.
VERIFIER_COMMIT_RE = re.compile(r"^[0-9a-f]{40}$")

SIGNING_SEED_LABEL = (
    b"arcs-verify:dagr-srs-verification-report-v0-2:golden-signing-seed:v1"
)

ISSUER_ID = "issuer:dagr:report-contract-v0-2"
KEY_ID = "issuer.dagr.report-contract-v0-2/receipt-signing/v1"

# Held identical across all six fixtures on purpose: the origin disclosure is
# read from the declared field alone, never inferred from the subject
# reference. Six receipts that share one subject_ref and differ only in what
# they declare must still disclose six different origins.
SHARED_SUBJECT_REF = "tool-call:call-origin-fixture-1"

ATTESTATION_LIMIT = (
    "The receipt attests only to governance conditions at the named "
    "admission boundary."
)

ORIGIN_STATES: tuple[tuple[str, str | None], ...] = tuple(
    (origin.replace("_", "-"), origin) for origin in DECLARED_ORIGINS
) + ((NOT_DECLARED.replace("_", "-"), None),)


class InvalidVerifierCommit(ValueError):
    """Raised when the supplied execution identity is not a 40-hex commit."""


def normalized_verifier_commit(value: str) -> str:
    """Return ``value`` unchanged if it is a full 40-hex lowercase SHA.

    Nothing is coerced, trimmed, or case-folded: the report must carry the
    supplied commit exactly, so a value that is not already contract-shaped is
    an error rather than something to repair.
    """

    if not isinstance(value, str) or not VERIFIER_COMMIT_RE.fullmatch(value):
        raise InvalidVerifierCommit(
            "--verifier-commit must be a full 40-hex lowercase git commit SHA "
            f"(got {value!r})"
        )
    return value


def _signing_key() -> Ed25519PrivateKey:
    seed = hashlib.sha256(SIGNING_SEED_LABEL).digest()
    return Ed25519PrivateKey.from_private_bytes(seed)


def _b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _trust_bundle(key: Ed25519PrivateKey) -> dict:
    from cryptography.hazmat.primitives import serialization

    public_bytes = key.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return {
        "issuers": [
            {
                "issuer_id": ISSUER_ID,
                "key_id": KEY_ID,
                "algorithm": "Ed25519",
                "public_key": _b64url(public_bytes),
                "not_before": "2026-01-01T00:00:00Z",
                "not_after": "2036-01-01T00:00:00Z",
                "trusted": True,
            }
        ]
    }


def _base_admission(slug: str, declared: str | None) -> dict:
    receipt = {
        "receipt_version": "srs.core.v5.1",
        "profile_id": "srs.mcp.sdk_enforcement",
        "profile_version": "v0.1",
        "receipt_id": f"urn:srs:receipt:admission:origin-{slug}",
        "receipt_type": "sdk_enforcement",
        "receipt_kind": "admission",
        "boundary_type": "mcp_tool_call",
        "protocol_binding": "mcp",
        "subject_ref": SHARED_SUBJECT_REF,
        "issuer_id": ISSUER_ID,
        "runtime_instance_id": "runtime:dagr:report-contract-v0-2",
        "boundary_id": "boundary:dagr:report-contract-v0-2",
        "logical_call_id": "call-origin-fixture-1",
        "issued_at": "2026-07-31T12:00:00Z",
        "artifact_classes_covered": ["tool_call_admission"],
        "artifact_classes_excluded": [
            "raw_prompt",
            "raw_output",
            "raw_tool_arguments",
            "raw_tool_result",
        ],
        "attestation_limits": [ATTESTATION_LIMIT],
        "extensions": {"mcp": {"binding_version": "fastmcp.middleware.v0.1"}},
        "requested_tool_name": "records_lookup",
        "tool_resolution_status": "not_observed",
        "argument_digest": "sha256:" + "0" * 64,
        "policy_pack_id": "policy:dagr:report-contract-v0-2",
        "policy_pack_version": "v0.1",
        "disposition": "admitted",
    }
    if declared is not None:
        receipt["subject_ref_origin"] = declared
    return receipt


def _sign(key: Ed25519PrivateKey, envelope: dict) -> dict:
    signed = copy.deepcopy(envelope)
    signed["receipt_signature"] = {
        "algorithm": "Ed25519",
        "canonicalization": "RFC8785-JCS",
        "key_id": KEY_ID,
        "signature": "",
    }
    preimage = copy.deepcopy(signed)
    del preimage["receipt_signature"]["signature"]
    signed["receipt_signature"]["signature"] = _b64url(
        key.sign(rfc8785.dumps(preimage))
    )
    return signed


def _write(path: Path, payload: dict) -> None:
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def generate(*, verifier_commit: str, output_dir: Path) -> list[dict]:
    """Write the six receipts, the trust bundle, the reports and expectations.

    ``verifier_commit`` is validated and then carried verbatim into every
    generated report and into ``expectations.json``.
    """

    commit = normalized_verifier_commit(verifier_commit)
    output_dir.mkdir(parents=True, exist_ok=True)

    key = _signing_key()
    trust_bundle = _trust_bundle(key)
    _write(output_dir / "trust-bundle.json", trust_bundle)

    schema_sha256 = dr2.envelope_schema_sha256_for_path(SCHEMA_V0_2_1)
    entries = []

    for slug, declared in ORIGIN_STATES:
        receipt = _sign(key, _base_admission(slug, declared))
        _write(output_dir / f"origin-{slug}-receipt.json", receipt)

        verification = verify_receipt(
            receipt,
            trust_bundle,
            schema_path=SCHEMA_V0_2_1,
            selected_profile=MCP_PROFILE,
        )
        report = dr2.build_verification_report(
            receipt,
            verification,
            selected_profile=MCP_PROFILE,
            trust_bundle=trust_bundle,
            verifier_commit=commit,
            envelope_schema_sha256=schema_sha256,
        )
        if report["verifier_commit"] != commit:
            raise SystemExit("generated report did not carry the supplied commit")
        _write(output_dir / f"origin-{slug}-report.json", report)

        errors = dr2.validate_verification_report(report)
        if errors:
            raise SystemExit(f"generated report failed its own schema: {errors}")

        entries.append(
            {
                "declared_subject_ref_origin": declared,
                "envelope_schema_sha256": schema_sha256,
                "envelope_schema_version": "v0.2.1",
                "receipt_artifact_hash": report["receipt_artifact_hash"],
                "receipt_path": f"origin-{slug}-receipt.json",
                "report_path": f"origin-{slug}-report.json",
                "subject_ref_origin_disclosed": report[
                    "subject_ref_origin_disclosed"
                ],
                "trust_bundle_digest": report["trust_bundle_digest"],
                "verdicts": report["verdicts"],
                "chain_status": report["chain_status"],
                "verification_report_digest": dr2.verification_report_digest(
                    report
                ),
                "verifier_configuration_digest": report[
                    "verifier_configuration_digest"
                ],
            }
        )

    _write(
        output_dir / "expectations.json",
        {
            "contract": dr2.REPORT_CONTRACT_ID,
            "entries": entries,
            "generator": "tools/generate_dagr_report_v0_2_goldens.py",
            "shared_subject_ref": SHARED_SUBJECT_REF,
            "signing_seed_label": SIGNING_SEED_LABEL.decode("ascii"),
            "verifier_commit": commit,
        },
    )
    return entries


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Deterministically generate the v0.2 DAGR SRS verification-report "
            "fixtures. Execution identity and destination are both mandatory "
            "inputs; nothing is inferred from repository state."
        )
    )
    parser.add_argument(
        "--verifier-commit",
        required=True,
        help=(
            "Full 40-hex lowercase git commit SHA of the arcs-verify "
            "implementation that produced these reports. Never inferred: for "
            "the authoritative goldens this is the implementation "
            "squash-merge commit, supplied by the post-merge closure PR."
        ),
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        help=(
            "Directory to write the receipts, trust bundle, reports and "
            "expectations into. Never defaulted, so a temporary generation "
            "cannot be mistaken for the authoritative golden surface."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    try:
        entries = generate(
            verifier_commit=args.verifier_commit, output_dir=args.output_dir
        )
    except InvalidVerifierCommit as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(f"wrote {len(entries)} report(s) to {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
